apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "namespace-reaper.fullname" . }}
  labels:
    {{- include "namespace-reaper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "namespace-reaper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "namespace-reaper.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "namespace-reaper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/namespace-reaper-live
            initialDelaySeconds: 5
            periodSeconds: 70
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/namespace-reaper-ready
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
