{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "namespace-reaper.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reaper
subjects:
- kind: ServiceAccount
  name: {{ include "namespace-reaper.serviceAccountName" . }}
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reaper
  apiGroup: rbac.authorization.k8s.io
{{- end -}}