---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-reaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-reaper
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reaper
subjects:
- kind: ServiceAccount
  name: namespace-reaper
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reaper
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-reaper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-reaper
  template:
    metadata:
      labels:
        app: namespace-reaper
    spec:
      serviceAccountName: namespace-reaper
      containers:
      - name: namespace-reaper
        image: namespace-reaper
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Never
